# Generated by Django 2.1.4 on 2018-12-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milicia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='miliciano',
            name='milicia_mil_cedula_bba8bb_idx',
        ),
        migrations.AddIndex(
            model_name='miliciano',
            index=models.Index(fields=['apellidos_pareja'], name='apellidos_pareja_idx'),
        ),
    ]
