# Generated by Django 2.1.4 on 2018-12-24 02:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('milicia', '0002_auto_20181223_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miliciano',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='miliciano',
            name='apellidos',
            field=models.CharField(max_length=30, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='miliciano',
            name='apellidos_pareja',
            field=models.CharField(max_length=30, verbose_name='Apellidos de su pareja'),
        ),
        migrations.AlterField(
            model_name='miliciano',
            name='cedula',
            field=models.IntegerField(verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='miliciano',
            name='cedula_pareja',
            field=models.IntegerField(verbose_name='Cédula de pareja'),
        ),
        migrations.AlterField(
            model_name='miliciano',
            name='fecha_ingreso',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Ingreso'),
        ),
        migrations.AlterField(
            model_name='miliciano',
            name='fecha_nacimiento',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='miliciano',
            name='miliciana_pareja',
            field=models.BooleanField(verbose_name='Pareja milician@'),
        ),
        migrations.AlterField(
            model_name='miliciano',
            name='nombres',
            field=models.CharField(max_length=30, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='miliciano',
            name='nombres_pareja',
            field=models.CharField(max_length=30, verbose_name='Nombres de su pareja'),
        ),
        migrations.AlterField(
            model_name='miliciano',
            name='observaciones',
            field=models.CharField(default='', max_length=200, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='miliciano',
            name='rango',
            field=models.CharField(max_length=20, verbose_name='Rango'),
        ),
        migrations.AlterField(
            model_name='miliciano',
            name='uniforme_camuflaje',
            field=models.BooleanField(default=False, verbose_name='Uniforme camuflado'),
        ),
        migrations.AlterField(
            model_name='miliciano',
            name='uniforme_miliciano',
            field=models.BooleanField(default=False, verbose_name='Uniforme Kaki'),
        ),
        migrations.AlterField(
            model_name='miliciano',
            name='uniforme_zamorano',
            field=models.BooleanField(default=False, verbose_name='Uniforme Zamorano'),
        ),
    ]
